config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # all visitor
  root 'welcomes#index'
  resources :users, only: %i(index show)
  resources :messages, only: [:new, :create]
  resources :helps, only: [] do
    collection do
      get :support
      get :ist
    end
  end

  # admin
  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount RailsAdmin::Engine => '/admin/model', as: :rails_admin
    mount Sidekiq::Web => '/admin/sidekiq/dashboard', as: :sidekiq_admin
  end
  namespace :admin do
    resources :dashboards, only: :index
    post '/sheets/diff', to: 'sheets#diff'
    resources :sheets do
      post :active, on: :member
      post :inactive, on: :member
    end
    resources :users do
      post :lock, on: :member
      post :unlock, on: :member
      get :login, on: :member
    end
    resources :messages, only: :index do
      post :active, on: :member
      post :inactive, on: :member
    end
    resources :mails, only: %i(new create)
  end

  # rival
  get '/rival/list' => 'rivals#list', as: :list_rival
  get '/rival/reverse_list' => 'rivals#reverse_list', as: :reverse_list_rival
  get '/rival/clear/:id' => 'rivals#clear', as: :clear_rival
  get '/rival/hard/:id' => 'rivals#hard', as: :hard_rival
  post '/rival/remove/:id' => 'rivals#remove', as: :remove_rival
  post '/rival/register/:id' => 'rivals#register', as: :register_rival
  resources :rivals, only: [] do
    put 'reverse'
  end

  # sheet
  get '/sheets/:iidxid/:type' => 'sheets#show', as: :sheet

  # score
  resources :scores, only: %i(edit update)

  # log
  resources :logs, only: %i(edit update destroy) do
    get :list, on: :member
    get :sheet, on: :member
    post :manager, on: :member
    post :iidxme, on: :member
    post :ist, on: :member
  end
  get '/logs/:id/:date' => 'logs#show', as: :logs

  # recommends
  resources :recommends, only: :index

  # API
  namespace :api do
    namespace :v1 do
      resources :abilities, only: %i[index create]
      # users
      resources :users, only: [] do
        collection do
          get :status
          get :me
          put '/users/change_rival/:iidxid', to: 'users#change_rival'
        end
      end
      # messages
      resources :messages, only: :index
      # logs
      resources :logs, only: [], param: :iidxid do
        get :cal_heatmap
      end
      get '/logs/:log_iidxid/:year/:month' => 'logs#full_calendar'
      get '/logs/graph/:log_iidxid/:year/:month' => 'logs#graph'
      # statics
      resources :statics, only: :index
      # sheets
      resources :sheets, only: :index
      get '/sheets/list' => 'sheets#list'
      # scores
      resources :scores, only: :show, param: :iidxid
      get '/scores/:iidxid/:sheet_id' => 'scores#detail'
      put '/scores/:iidxid/:sheet_id/:state' => 'scores#update'
      post '/scores/sync/iidxme/:iidxid' => 'scores#sync_iidxme'

      post '/maintenance', to: 'maintenance#change'
      resources :health_check, only: :index
    end
  end

  mount Peek::Railtie => '/peek'
  mount Sidekiq::Prometheus::Exporter => '/sidekiq/metrics'
end

app/models/message.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: messages
#
#  id         :bigint(8)        not null, primary key
#  body       :string
#  email      :string
#  ip         :inet             not null
#  user_id    :bigint(8)
#  state      :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_messages_on_user_id  (user_id)
#

class Message < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/messages_controller.rb
# frozen_string_literal: true

class Admin::MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :load_message, except: [:index]

  def index
    @search = Message.ransack(params[:q])
    @messages = @search.result
  end

  def active
    @message.update!(state: true)
    redirect_to admin_messages_path
  end

  def inactive
    @message.update!(state: false)
    redirect_to admin_messages_path
  end

  private

  def load_message
    return unless params[:id]

    @message = Message.find_by(id: params[:id])
  end
end

app/controllers/api/v1/messages_controller.rb
# frozen_string_literal: true

class Api::V1::MessagesController < Api::V1::BaseController
  def index
    authenticate_member!
    render json: { num: Message.where(state: false).count }
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

require 'slack/message_dispatcher'

class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    message = Message.new(message_params)
    message.user_id = current_user.id if user_signed_in?
    message.ip = request.remote_ip
    result = message.save
    if result
      Slack::MessageDispatcher.send(message.id)
      flash[:notice] = '承りました。対応はしばしお待ちください。'
    else
      flash[:alert] = '何らかの不具合で送信できていません。Twitterなどにご連絡下さい。'
    end
    redirect_to root_path
  end

  def password; end

  private

  def message_params
    params.require(:message).permit(
      :email, :body
    )
  end
end

app/views/messages/new.html.slim
- @title = '連絡フォーム'
h3.subtitle.is-3 = icon 'phone', @title

section.accordions
  article.accordion.is-info
    .accordion-header
      p = icon 'key', 'パスワードを忘れた方向け'
      button.toggle aria-label='toggle'
    .accordion-body
      .accordion-content
        p 以下の手順でTwitterで連絡してください。
        blockquote.twitter-tweet data-lang='ja'
          p lang='ja' dir='ltr'
            a href='https://twitter.com/sukemasa_P'
              | @sukemasa_P
            |  お問い合わせありがとうございます。本人確認のため
            a href='https://t.co/btjiBmWBvp'
              | https://t.co/btjiBmWBvp
            br
            | のような形でIIDXIDが記載したスクリーンショットを頂けるでしょうか。
            br
            | 削除することもできますし、dm経由で一時的なパスワードに変更することも可能です。
          | — IIDX☆12参考表 (@IIDX_12)
          a href='https://twitter.com/IIDX_12/status/774630178425155584'
            | 2016年9月10日
        script src='//platform.twitter.com/widgets.js' charset='utf-8' async=true

.content
  ul
    li 既にiidxidが使われている
    li 何らかの不具合やバグ報告など
  | 対応は
  = link_to 'http://twitter.com/IIDX_12'
    = icon 'twitter', 'Twitter', style: 'fab'
  | のほうが迅速なことが多いです。
  br
  font color='red'
    | 返信が迷惑メールに振り分けられていることが有ります。
    br
    | @mail.iidx.appを許可リストに入れるか、迷惑メールも合わせてチェック下さい。

= form_for @message, html: { class: 'conntact' } do |f|
  .field
    label.label 連絡先(任意)
    .control = f.email_field :email, placeholder: '返答が必要な際には必ずご記入下さい。', class: 'input'
  .field
    label.label 内容
    .control = f.text_area :body, rows: 3, class: 'textarea'
  .field
    .control
      button.button.is-primary type='submit' = icon 'sign-in-alt', '送信'
      = link_to 'キャンセル', new_message_path, class: 'button'