config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # all visitor
  root 'welcomes#index'
  resources :users, only: %i(index show)
  resources :messages, only: [:new, :create]
  resources :helps, only: [] do
    collection do
      get :support
      get :ist
    end
  end

  # admin
  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount RailsAdmin::Engine => '/admin/model', as: :rails_admin
    mount Sidekiq::Web => '/admin/sidekiq/dashboard', as: :sidekiq_admin
  end
  namespace :admin do
    resources :dashboards, only: :index
    post '/sheets/diff', to: 'sheets#diff'
    resources :sheets do
      post :active, on: :member
      post :inactive, on: :member
    end
    resources :users do
      post :lock, on: :member
      post :unlock, on: :member
      get :login, on: :member
    end
    resources :messages, only: :index do
      post :active, on: :member
      post :inactive, on: :member
    end
    resources :mails, only: %i(new create)
  end

  # rival
  get '/rival/list' => 'rivals#list', as: :list_rival
  get '/rival/reverse_list' => 'rivals#reverse_list', as: :reverse_list_rival
  get '/rival/clear/:id' => 'rivals#clear', as: :clear_rival
  get '/rival/hard/:id' => 'rivals#hard', as: :hard_rival
  post '/rival/remove/:id' => 'rivals#remove', as: :remove_rival
  post '/rival/register/:id' => 'rivals#register', as: :register_rival
  resources :rivals, only: [] do
    put 'reverse'
  end

  # sheet
  get '/sheets/:iidxid/:type' => 'sheets#show', as: :sheet

  # score
  resources :scores, only: %i(edit update)

  # log
  resources :logs, only: %i(edit update destroy) do
    get :list, on: :member
    get :sheet, on: :member
    post :manager, on: :member
    post :iidxme, on: :member
    post :ist, on: :member
  end
  get '/logs/:id/:date' => 'logs#show', as: :logs

  # recommends
  resources :recommends, only: :index

  # API
  namespace :api do
    namespace :v1 do
      resources :abilities, only: %i[index create]
      # users
      resources :users, only: [] do
        collection do
          get :status
          get :me
          put '/users/change_rival/:iidxid', to: 'users#change_rival'
        end
      end
      # messages
      resources :messages, only: :index
      # logs
      resources :logs, only: [], param: :iidxid do
        get :cal_heatmap
      end
      get '/logs/:log_iidxid/:year/:month' => 'logs#full_calendar'
      get '/logs/graph/:log_iidxid/:year/:month' => 'logs#graph'
      # statics
      resources :statics, only: :index
      # sheets
      resources :sheets, only: :index
      get '/sheets/list' => 'sheets#list'
      # scores
      resources :scores, only: :show, param: :iidxid
      get '/scores/:iidxid/:sheet_id' => 'scores#detail'
      put '/scores/:iidxid/:sheet_id/:state' => 'scores#update'
      post '/scores/sync/iidxme/:iidxid' => 'scores#sync_iidxme'

      post '/maintenance', to: 'maintenance#change'
      resources :health_check, only: :index
    end
  end

  mount Peek::Railtie => '/peek'
  mount Sidekiq::Prometheus::Exporter => '/sidekiq/metrics'
end

app/models/concerns/user/api.rb
# frozen_string_literal: true

module User::Api
  extend ActiveSupport::Concern

  included do
    def graph(start_month, end_month)
      categories = logs.create_between(start_month, end_month).map { |b| b[0].to_s.slice(0, 7) }
      column = logs.column(start_month, end_month)
      spline = logs.spline(start_month, end_month)
      {
        categories: categories,
        pie: scores.is_active.is_current_version.pie,
        column: column,
        column_max: column.flatten.max,
        spline: spline,
        spline_max: spline.flatten.max
      }
    end

    def schema
      image_url = avatar.attached? ? Rails.application.routes.url_helpers.rails_blob_path(avatar, disposition: :inline, only_path: true) : nil
      {
        id: id,
        iidxid: iidxid,
        role: role,
        djname: djname,
        grade: grade,
        pref: pref,
        image_url: image_url,
        created_at: created_at,
        follows: follow_users.pluck(:iidxid),
        followers: follower_users.pluck(:iidxid)
      }
    end
  end
end

app/models/concerns/user/devise_methods.rb
# frozen_string_literal: true

module User::DeviseMethods
  extend ActiveSupport::Concern

  included do
    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      login = conditions.delete(:login)
      if login
        find_by('username = :value OR iidxid = :value OR email = :value', value: login)
      else
        find_by(conditions)
      end
    end

    def update_without_current_password(params, *options)
      params.delete(:current_password)
      params.delete(:password) if params[:password].blank?
      params.delete(:password_confirmation) if params[:password_confirmation].blank?

      clean_up_passwords
      update_attributes(params, *options)
    end

    def email_required?
      false
    end

    def email_changed?
      false
    end
  end
end

app/models/concerns/user/follow_methods.rb
# frozen_string_literal: true

module User::FollowMethods
  extend ActiveSupport::Concern
  included do
    def change_follow(target_user)
      following?(target_user.id) ? unfollow(target_user.iidxid) : follow(target_user.iidxid)
    end

    def following?(user_id)
      follow_users.pluck(:id).include?(user_id)
    end

    def follow(iidxid)
      target_user_id = User.select(:id).find_by(iidxid: iidxid).id
      return false if Follow.exists?(user_id: id, target_user_id: target_user_id)

      Follow.create(user_id: id, target_user_id: target_user_id)
    end

    def unfollow(iidxid)
      target_user_id = User.select(:id).find_by(iidxid: iidxid).id
      return false unless Follow.exists?(user_id: id, target_user_id: target_user_id)

      Follow.find_by(user_id: id, target_user_id: target_user_id).destroy
    end
  end
end

app/models/concerns/user/ist.rb
# frozen_string_literal: true

require 'ist_client'

module User::Ist
  extend ActiveSupport::Concern
  FROM_IST_TO_AB = {
    '旋律のドグマ～Miserables～' => '旋律のドグマ ～Misérables～',
    '火影' => '焱影',
    '炎影' => '焱影'
  }.freeze
  SEARCH_PARAMS = {
    q: {
      music_score_level_eq: 12,
      music_score_play_type_status_eq: 0,
      version_eq: Abilitysheet::Application.config.iidx_version
    }
  }.freeze

  # FIXME: 米国などの見つからなかったやつは海外に全部まとめている
  def find_pref(pref)
    User::Static::PREF.index(pref) || 0
  end

  # NOTE: 見つからなかったやつは無段位
  def find_grade(grade)
    User::Static::GRADE.index(grade.split[1]) || User::Static::GRADE.size - 1
  end

  def update_user(user)
    old_djname = djname
    self.djname = old_djname unless update(djname: user['user_activity']['djname'])
    pref = find_pref(user['user_activity']['pref_status'])
    grade = find_grade(user['user_activity']['sp_grade_status'])
    update!(grade: grade, pref: pref)
    avatar.attach(io: URI.open(user['image_path']), filename: 'avatar.png') unless Rails.env.development?
  end

  def find_sheet_id(score, sheets)
    if score['title'] == 'gigadelic' || score['title'] == 'Innocent Walls'
      difficulty_type = score['difficulty_type_status'] == 'HYPER' ? '[H]' : '[A]'
      sheets[score['title'] + difficulty_type]
    elsif FROM_IST_TO_AB.key?(score['title'])
      sheets[FROM_IST_TO_AB[score['title']]]
    else
      sheets[score['title']]
    end
  end

  included do
    def update_ist
      user = ist_client.get_user(iidxid)
      return false if user.dig('error') == 'Not Found'
      return false if user['iidxid'] != iidxid

      result = ist_client.get_scores(iidxid, SEARCH_PARAMS)
      return false if result.dig('error') == 'Not Found'

      update_user(user)

      sheets = Sheet.active.pluck(:title, :id).to_h
      result['scores'].each do |score|
        sheet_id = find_sheet_id(score, sheets)
        # 削除曲だけunlessになる可能性がある
        next unless sheet_id

        scores.find_or_create_by!(
          sheet_id: sheet_id,
          version: Abilitysheet::Application.config.iidx_version
        ).update_with_logs(
          sheet_id: sheet_id,
          state: ::Static::LAMP_OFFICIAL.index(score['clear_type_status']),
          score: score['score'],
          bp: score['miss_count']
        )
      end
    end

    def ist_client
      IstClient.new
    end
  end
end

app/models/concerns/user/list.rb
# frozen_string_literal: true

module User::List
  extend ActiveSupport::Concern

  included do
    class << self
      def users_list(type, options = {})
        __send__(type, options)
      end

      def recent200
        query = <<~QUERY
          SELECT
          users.id, users.djname, users.iidxid, users.pref, users.grade,
          scores.updated_at, scores.state, sheets.title
          FROM users, scores, sheets
          WHERE users.id = scores.user_id
          AND scores.state != 7
          AND sheets.id = scores.sheet_id
          ORDER BY scores.updated_at DESC
          LIMIT 6400
        QUERY
        query.chomp.tr("\n", ' ')
        users = ActiveRecord::Base.connection.execute(query.chomp.tr("\n", ' ')).to_a
        recent_users = []
        ret = {}
        users.each do |user|
          break if recent_users.size >= 200
          next if recent_users.include?(user['id'])

          recent_users.push(user['id'])
          user['updated_at'] = user['updated_at'].to_date
          ret[user['id']] = user
        end
        ret
      end

      private

      def rivals(users)
        scores_map = {}
        users.each { |user| scores_map[user.id] = user.scores.last_updated }
        scores_map
      end
    end
  end
end

app/models/concerns/user/role.rb
# frozen_string_literal: true

module User::Role
  extend ActiveSupport::Concern

  OWNER = 100
  ADMIN = 75
  MEMBER = 50
  SPECIAL = 25
  GENERAL = 0

  included do
    def owner?
      OWNER <= role
    end

    def admin?
      ADMIN <= role
    end

    def member?
      MEMBER <= role
    end

    def special?
      SPECIAL == role || OWNER == role
    end
  end
end

app/models/concerns/user/static.rb
# frozen_string_literal: true

module User::Static
  PREF = %w[
    海外
    北海道 青森県 岩手県 宮城県
    秋田県 山形県 福島県 茨城県
    栃木県 群馬県 埼玉県 千葉県
    東京都 神奈川県 新潟県 富山県
    石川県 福井県 山梨県 長野県
    岐阜県 静岡県 愛知県 三重県
    滋賀県 京都府 大阪府 兵庫県
    奈良県 和歌山県 鳥取県 島根県
    岡山県 広島県 山口県 徳島県
    香川県 愛媛県 高知県 福岡県
    佐賀県 長崎県 熊本県 大分県
    宮崎県 鹿児島県 沖縄県
  ].freeze

  GRADE = %w[
    皆伝 中伝
    十段 九段
    八段 七段 六段 五段 四段 三段 二段 初段
    一級 二級 三級 四級 五級 六級 七級
    無段位
  ].freeze

  GRADE_COLOR = %w[
    #ffd900 #dcdddd
    #ff6347 #ff6347
    #afeeee #afeeee #afeeee #afeeee #afeeee #afeeee #afeeee #afeeee
    #98fb98 #98fb98 #98fb98 #98fb98 #98fb98 #98fb98 #98fb98
    #fbefef
  ].freeze
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :check_xhr, except: %i[index login]
  before_action :load_user, except: %i[index new create]

  def index
    @q = User.ransack(params[:q])
    @q.sorts = ['id desc'] if @q.sorts.empty?
    @users = @q.result.page(params[:page])
  end

  def new
    render :show_modal_form
  end

  def create
    @user = User.new(user_params)
    @user.save
    render :reload
  end

  def edit
    render :show_modal_form
  end

  def update
    @user.update_without_current_password(user_params)
    render :reload
  end

  def destroy
    @user.destroy
    render :reload
  end

  def lock
    @user.lock_access!
    render :reload
  end

  def unlock
    @user.unlock_access!
    render :reload
  end

  def login
    sign_out current_user
    sign_in @user
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(
      :email, :iidxid, :username, :djname, :grade, :pref, :password
    )
  end

  def load_user
    return unless params[:id]

    @user = User.find_by(id: params[:id])
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::V1::BaseController
  def status
    render json: { status: current_user.try(:iidxid) }
  end

  def me
    render json: { current_user: current_user.try(:schema) }
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      flash[:notice] = '再発行メールを送信しました、数分ほどかかります'
      flash[:alert] = '届いていない場合は迷惑メールフォルダをご確認下さい'
    elsif !User.exists?(email: resource.email)
      flash[:alert] = '登録されていないメールアドレスです'
    else
      flash[:alert] = '何らかの不具合によりメールが送れませんでした．管理人に連絡下さい'
    end
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

require 'slack/user_dispatcher'

class Users::RegistrationsController < Devise::RegistrationsController
  def create
    pre_user = User.select(:id).count
    super
    after_user = User.select(:id).count
    sync_score if pre_user < after_user
  end

  def destroy
    Slack::UserDispatcher.delete_user_notify(current_user.id)
    super
  end

  private

  def sync_score
    iidxid = request.env['rack.request.form_hash']['user']['iidxid']
    user = User.find_by(iidxid: iidxid)
    return unless user

    Slack::UserDispatcher.new_register_notify(user.id)
    IstSyncJob.perform_later(user)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @title = '最近更新した200人'
    if params[:query]&.present?
      @users = User.where(iidxid: params[:query])
      @scores_map = User.users_list(:rivals, @users)
    else
      @users = User.recent200.deep_symbolize_keys
    end
  end

  def show
    @user = User.find_by_iidxid!(params[:id])
    @title = "DJ.#{@user.djname} プロフィール"
  end
end

app/views/users/_list.html.slim
table.table.is-hoverable.is-fullwidth.datatable
  thead
    th.has-text-centered DJNAME
    th.has-text-centered IIDX-ID
    th.has-text-centered 段位
    th.has-text-centered 所属
    th.has-text-centered 最終更新日
    th.has-text-centered 最終更新楽曲
    th.has-text-centered ランプ情報
  tbody
    - @users.each_key do |key|
      - user = @users[key]
      - iidxid = user[:iidxid]
      tr
        td.has-text-centered = link_to user[:djname], user_path(iidxid)
        td.has-text-centered = iidxid
        td.has-text-centered bgcolor=User::Static::GRADE_COLOR[user[:grade].to_i] = User::Static::GRADE[user[:grade].to_i]
        td.has-text-centered = User::Static::PREF[user[:pref].to_i]
        td.has-text-centered = link_to user[:updated_at], logs_path(iidxid, user[:updated_at])
        td.has-text-centered = user[:title]
        td.has-text-centered bgcolor=Static::COLOR[user[:state].to_i]
javascript:
  if ($('[id^=DataTables_Table]').length === 0) {
    $('.datatable').dataTable({
      order: [4, 'desc'],
      aLengthMenu: [25],
      columnDefs: [
        {
          type: 'grade',
          targets: [2]
        }
      ]
    });
  }

app/views/users/_show_left.html.slim
- user = user.decorate
= image_tag(url_for(user.avatar), class: 'icon-img') if user.avatar.attached?
. style='margin-top: 20px'
  h3.subtitle.is-3
    b = user.djname
.
  h4.subtitle.is-4
    = user.iidxid
    | &nbsp;
    - if current_user && current_user != user
      = link_to rival_reverse_path(user.iidxid), method: :put, class: 'button'
        - if current_user.follows.pluck(:target_user_id).include?(user.id)
          = icon 'user-times', 'ライバルから削除'
        - else
          = icon 'user-plus', 'ライバルに追加'
. style='padding-bottom: 3px'
    = react_component_wrapper 'TwitterSharedButton', text: "DJ.#{user.djname} ☆12参考表プロフィール"
. style='padding-bottom: 3px'
  = link_to 'ノマゲ参考表', sheet_path(user.iidxid, type: 'clear'), class: 'button is-link'
  = link_to 'ハード参考表', sheet_path(user.iidxid, type: 'hard'), class: 'button is-danger'
- if current_user && current_user != user
  . style='padding-bottom: 3px'
      .
        = link_to 'ノマゲ比較', clear_rival_path(user.iidxid), class: 'button is-link'
        = link_to 'ハード比較', hard_rival_path(user.iidxid), class: 'button is-danger'
hr
. = icon 'street-view', user.grade
. = icon 'map-marker-alt', user.pref
. = icon 'clock', user.joined_on
hr
table style='margin: 0 auto; text-align: center'
  tbody
    tr
      td
        h2#rival-number = user.follows.size
      td
        h2#reverse-rival-number = user.followers.size
    tr
      td ライバル
      td 逆ライバル

app/views/users/index.html.slim
h3.subtitle.is-3 = icon 'users', @title

= form_tag users_path, method: :get, class: 'right'
  = icon 'search', 'IIDXIDから検索'
  .field
    = text_field_tag :query, params[:query], placeholder: '0000-0000', class: 'input', style: 'width: 150px'
    button.button.is-primary
      = icon 'search', '検索'
hr
- if @scores_map
  = render 'shared/list'
- else
  = render 'users/list'

javascript:
  function format(val) {
    const mapping = {
      '皆伝': 0,
      '中伝': 1,
      '十段': 2,
      '九段': 3,
      '八段': 4,
      '七段': 5,
      '六段': 6,
      '五段': 7,
      '四段': 8,
      '三段': 9,
      '二段': 10,
      '初段': 11,
      '初級': 12,
      '二級': 13,
      '三級': 14,
      '四級': 15,
      '五級': 16,
      '六級': 17,
      '七級': 18,
      '無段位': 19,
    };
    const res = mapping[val];
    return res || -1;
  }

  $.extend($.fn.dataTable.ext.type.order, {
    'grade-asc'(x, y) {
      x = format(x);
      y = format(y);
      return ((x < y) ? -1 : ((x > y) ? 1 : 0));
    },
    'grade-desc'(x, y) {
      x = format(x);
      y = format(y);
      return ((x < y) ? 1 : ((x > y) ? -1 : 0));
    },
  });

app/views/users/show.html.slim
.columns
  .column.is-one-quarter
    = render partial: 'show_left', locals: { user: @user }
  .column
    = react_component_wrapper 'Profile', user: @user.schema