config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # all visitor
  root 'welcomes#index'
  resources :users, only: %i(index show)
  resources :messages, only: [:new, :create]
  resources :helps, only: [] do
    collection do
      get :support
      get :ist
    end
  end

  # admin
  require 'sidekiq/web'
  authenticate :user, ->(u) { u.admin? } do
    mount RailsAdmin::Engine => '/admin/model', as: :rails_admin
    mount Sidekiq::Web => '/admin/sidekiq/dashboard', as: :sidekiq_admin
  end
  namespace :admin do
    resources :dashboards, only: :index
    post '/sheets/diff', to: 'sheets#diff'
    resources :sheets do
      post :active, on: :member
      post :inactive, on: :member
    end
    resources :users do
      post :lock, on: :member
      post :unlock, on: :member
      get :login, on: :member
    end
    resources :messages, only: :index do
      post :active, on: :member
      post :inactive, on: :member
    end
    resources :mails, only: %i(new create)
  end

  # rival
  get '/rival/list' => 'rivals#list', as: :list_rival
  get '/rival/reverse_list' => 'rivals#reverse_list', as: :reverse_list_rival
  get '/rival/clear/:id' => 'rivals#clear', as: :clear_rival
  get '/rival/hard/:id' => 'rivals#hard', as: :hard_rival
  post '/rival/remove/:id' => 'rivals#remove', as: :remove_rival
  post '/rival/register/:id' => 'rivals#register', as: :register_rival
  resources :rivals, only: [] do
    put 'reverse'
  end

  # sheet
  get '/sheets/:iidxid/:type' => 'sheets#show', as: :sheet

  # score
  resources :scores, only: %i(edit update)

  # log
  resources :logs, only: %i(edit update destroy) do
    get :list, on: :member
    get :sheet, on: :member
    post :manager, on: :member
    post :iidxme, on: :member
    post :ist, on: :member
  end
  get '/logs/:id/:date' => 'logs#show', as: :logs

  # recommends
  resources :recommends, only: :index

  # API
  namespace :api do
    namespace :v1 do
      resources :abilities, only: %i[index create]
      # users
      resources :users, only: [] do
        collection do
          get :status
          get :me
          put '/users/change_rival/:iidxid', to: 'users#change_rival'
        end
      end
      # messages
      resources :messages, only: :index
      # logs
      resources :logs, only: [], param: :iidxid do
        get :cal_heatmap
      end
      get '/logs/:log_iidxid/:year/:month' => 'logs#full_calendar'
      get '/logs/graph/:log_iidxid/:year/:month' => 'logs#graph'
      # statics
      resources :statics, only: :index
      # sheets
      resources :sheets, only: :index
      get '/sheets/list' => 'sheets#list'
      # scores
      resources :scores, only: :show, param: :iidxid
      get '/scores/:iidxid/:sheet_id' => 'scores#detail'
      put '/scores/:iidxid/:sheet_id/:state' => 'scores#update'
      post '/scores/sync/iidxme/:iidxid' => 'scores#sync_iidxme'

      post '/maintenance', to: 'maintenance#change'
      resources :health_check, only: :index
    end
  end

  mount Peek::Railtie => '/peek'
  mount Sidekiq::Prometheus::Exporter => '/sidekiq/metrics'
end

app/models/concerns/user/api.rb
# frozen_string_literal: true

module User::Api
  extend ActiveSupport::Concern

  included do
    def graph(start_month, end_month)
      categories = logs.create_between(start_month, end_month).map { |b| b[0].to_s.slice(0, 7) }
      column = logs.column(start_month, end_month)
      spline = logs.spline(start_month, end_month)
      {
        categories: categories,
        pie: scores.is_active.is_current_version.pie,
        column: column,
        column_max: column.flatten.max,
        spline: spline,
        spline_max: spline.flatten.max
      }
    end

    def schema
      image_url = avatar.attached? ? Rails.application.routes.url_helpers.rails_blob_path(avatar, disposition: :inline, only_path: true) : nil
      {
        id: id,
        iidxid: iidxid,
        role: role,
        djname: djname,
        grade: grade,
        pref: pref,
        image_url: image_url,
        created_at: created_at,
        follows: follow_users.pluck(:iidxid),
        followers: follower_users.pluck(:iidxid)
      }
    end
  end
end

app/models/concerns/user/devise_methods.rb
# frozen_string_literal: true

module User::DeviseMethods
  extend ActiveSupport::Concern

  included do
    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      login = conditions.delete(:login)
      if login
        find_by('username = :value OR iidxid = :value OR email = :value', value: login)
      else
        find_by(conditions)
      end
    end

    def update_without_current_password(params, *options)
      params.delete(:current_password)
      params.delete(:password) if params[:password].blank?
      params.delete(:password_confirmation) if params[:password_confirmation].blank?

      clean_up_passwords
      update_attributes(params, *options)
    end

    def email_required?
      false
    end

    def email_changed?
      false
    end
  end
end

app/models/concerns/user/follow_methods.rb
# frozen_string_literal: true

module User::FollowMethods
  extend ActiveSupport::Concern
  included do
    def change_follow(target_user)
      following?(target_user.id) ? unfollow(target_user.iidxid) : follow(target_user.iidxid)
    end

    def following?(user_id)
      follow_users.pluck(:id).include?(user_id)
    end

    def follow(iidxid)
      target_user_id = User.select(:id).find_by(iidxid: iidxid).id
      return false if Follow.exists?(user_id: id, target_user_id: target_user_id)

      Follow.create(user_id: id, target_user_id: target_user_id)
    end

    def unfollow(iidxid)
      target_user_id = User.select(:id).find_by(iidxid: iidxid).id
      return false unless Follow.exists?(user_id: id, target_user_id: target_user_id)

      Follow.find_by(user_id: id, target_user_id: target_user_id).destroy
    end
  end
end

app/models/concerns/user/ist.rb
# frozen_string_literal: true

require 'ist_client'

module User::Ist
  extend ActiveSupport::Concern
  FROM_IST_TO_AB = {
    '旋律のドグマ～Miserables～' => '旋律のドグマ ～Misérables～',
    '火影' => '焱影',
    '炎影' => '焱影'
  }.freeze
  SEARCH_PARAMS = {
    q: {
      music_score_level_eq: 12,
      music_score_play_type_status_eq: 0,
      version_eq: Abilitysheet::Application.config.iidx_version
    }
  }.freeze

  # FIXME: 米国などの見つからなかったやつは海外に全部まとめている
  def find_pref(pref)
    User::Static::PREF.index(pref) || 0
  end

  # NOTE: 見つからなかったやつは無段位
  def find_grade(grade)
    User::Static::GRADE.index(grade.split[1]) || User::Static::GRADE.size - 1
  end

  def update_user(user)
    old_djname = djname
    self.djname = old_djname unless update(djname: user['user_activity']['djname'])
    pref = find_pref(user['user_activity']['pref_status'])
    grade = find_grade(user['user_activity']['sp_grade_status'])
    update!(grade: grade, pref: pref)
    avatar.attach(io: URI.open(user['image_path']), filename: 'avatar.png') unless Rails.env.development?
  end

  def find_sheet_id(score, sheets)
    if score['title'] == 'gigadelic' || score['title'] == 'Innocent Walls'
      difficulty_type = score['difficulty_type_status'] == 'HYPER' ? '[H]' : '[A]'
      sheets[score['title'] + difficulty_type]
    elsif FROM_IST_TO_AB.key?(score['title'])
      sheets[FROM_IST_TO_AB[score['title']]]
    else
      sheets[score['title']]
    end
  end

  included do
    def update_ist
      user = ist_client.get_user(iidxid)
      return false if user.dig('error') == 'Not Found'
      return false if user['iidxid'] != iidxid

      result = ist_client.get_scores(iidxid, SEARCH_PARAMS)
      return false if result.dig('error') == 'Not Found'

      update_user(user)

      sheets = Sheet.active.pluck(:title, :id).to_h
      result['scores'].each do |score|
        sheet_id = find_sheet_id(score, sheets)
        # 削除曲だけunlessになる可能性がある
        next unless sheet_id

        scores.find_or_create_by!(
          sheet_id: sheet_id,
          version: Abilitysheet::Application.config.iidx_version
        ).update_with_logs(
          sheet_id: sheet_id,
          state: ::Static::LAMP_OFFICIAL.index(score['clear_type_status']),
          score: score['score'],
          bp: score['miss_count']
        )
      end
    end

    def ist_client
      IstClient.new
    end
  end
end

app/models/concerns/user/list.rb
# frozen_string_literal: true

module User::List
  extend ActiveSupport::Concern

  included do
    class << self
      def users_list(type, options = {})
        __send__(type, options)
      end

      def recent200
        query = <<~QUERY
          SELECT
          users.id, users.djname, users.iidxid, users.pref, users.grade,
          scores.updated_at, scores.state, sheets.title
          FROM users, scores, sheets
          WHERE users.id = scores.user_id
          AND scores.state != 7
          AND sheets.id = scores.sheet_id
          ORDER BY scores.updated_at DESC
          LIMIT 6400
        QUERY
        query.chomp.tr("\n", ' ')
        users = ActiveRecord::Base.connection.execute(query.chomp.tr("\n", ' ')).to_a
        recent_users = []
        ret = {}
        users.each do |user|
          break if recent_users.size >= 200
          next if recent_users.include?(user['id'])

          recent_users.push(user['id'])
          user['updated_at'] = user['updated_at'].to_date
          ret[user['id']] = user
        end
        ret
      end

      private

      def rivals(users)
        scores_map = {}
        users.each { |user| scores_map[user.id] = user.scores.last_updated }
        scores_map
      end
    end
  end
end

app/models/concerns/user/role.rb
# frozen_string_literal: true

module User::Role
  extend ActiveSupport::Concern

  OWNER = 100
  ADMIN = 75
  MEMBER = 50
  SPECIAL = 25
  GENERAL = 0

  included do
    def owner?
      OWNER <= role
    end

    def admin?
      ADMIN <= role
    end

    def member?
      MEMBER <= role
    end

    def special?
      SPECIAL == role || OWNER == role
    end
  end
end

app/models/concerns/user/static.rb
# frozen_string_literal: true

module User::Static
  PREF = %w[
    海外
    北海道 青森県 岩手県 宮城県
    秋田県 山形県 福島県 茨城県
    栃木県 群馬県 埼玉県 千葉県
    東京都 神奈川県 新潟県 富山県
    石川県 福井県 山梨県 長野県
    岐阜県 静岡県 愛知県 三重県
    滋賀県 京都府 大阪府 兵庫県
    奈良県 和歌山県 鳥取県 島根県
    岡山県 広島県 山口県 徳島県
    香川県 愛媛県 高知県 福岡県
    佐賀県 長崎県 熊本県 大分県
    宮崎県 鹿児島県 沖縄県
  ].freeze

  GRADE = %w[
    皆伝 中伝
    十段 九段
    八段 七段 六段 五段 四段 三段 二段 初段
    一級 二級 三級 四級 五級 六級 七級
    無段位
  ].freeze

  GRADE_COLOR = %w[
    #ffd900 #dcdddd
    #ff6347 #ff6347
    #afeeee #afeeee #afeeee #afeeee #afeeee #afeeee #afeeee #afeeee
    #98fb98 #98fb98 #98fb98 #98fb98 #98fb98 #98fb98 #98fb98
    #fbefef
  ].freeze
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :check_xhr, except: %i[index login]
  before_action :load_user, except: %i[index new create]

  def index
    @q = User.ransack(params[:q])
    @q.sorts = ['id desc'] if @q.sorts.empty?
    @users = @q.result.page(params[:page])
  end

  def new
    render :show_modal_form
  end

  def create
    @user = User.new(user_params)
    @user.save
    render :reload
  end

  def edit
    render :show_modal_form
  end

  def update
    @user.update_without_current_password(user_params)
    render :reload
  end

  def destroy
    @user.destroy
    render :reload
  end

  def lock
    @user.lock_access!
    render :reload
  end

  def unlock
    @user.unlock_access!
    render :reload
  end

  def login
    sign_out current_user
    sign_in @user
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(
      :email, :iidxid, :username, :djname, :grade, :pref, :password
    )
  end

  def load_user
    return unless params[:id]

    @user = User.find_by(id: params[:id])
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::V1::BaseController
  def status
    render json: { status: current_user.try(:iidxid) }
  end

  def me
    render json: { current_user: current_user.try(:schema) }
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      flash[:notice] = '再発行メールを送信しました、数分ほどかかります'
      flash[:alert] = '届いていない場合は迷惑メールフォルダをご確認下さい'
    elsif !User.exists?(email: resource.email)
      flash[:alert] = '登録されていないメールアドレスです'
    else
      flash[:alert] = '何らかの不具合によりメールが送れませんでした．管理人に連絡下さい'
    end
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

require 'slack/user_dispatcher'

class Users::RegistrationsController < Devise::RegistrationsController
  def create
    pre_user = User.select(:id).count
    super
    after_user = User.select(:id).count
    sync_score if pre_user < after_user
  end

  def destroy
    Slack::UserDispatcher.delete_user_notify(current_user.id)
    super
  end

  private

  def sync_score
    iidxid = request.env['rack.request.form_hash']['user']['iidxid']
    user = User.find_by(iidxid: iidxid)
    return unless user

    Slack::UserDispatcher.new_register_notify(user.id)
    IstSyncJob.perform_later(user)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @title = '最近更新した200人'
    if params[:query]&.present?
      @users = User.where(iidxid: params[:query])
      @scores_map = User.users_list(:rivals, @users)
    else
      @users = User.recent200.deep_symbolize_keys
    end
  end

  def show
    @user = User.find_by_iidxid!(params[:id])
    @title = "DJ.#{@user.djname} プロフィール"
  end
end

app/views/admin/users/_form.html.slim
- unless user
  - user = User.new
  - title = 'ユーザの追加'
  - submit = '追加'
- else
  - title = 'ユーザの更新'
  - submit = '更新'

.modal-background
.modal-content
  .box
    h2.subtitle.is-5 = icon 'user', title
    = form_for [:admin, user], remote: true do |f|
      .field
        label.label メールアドレス
        .control = f.email_field :email, autofocus: true, placeholder: 'パスワード再発行/ログイン用', class: 'input'
      .field
        label.label アカウント名(半角英数字)
        .control = f.text_field :username, autofocus: true, placeholder: '15文字以内, ex. sample', class: 'input'
      .columns
        .column
          label.label DJNAME
          .control = f.text_field :djname, autofocus: true, placeholder: '6文字以内, ex. SAMPLE', class: 'input'
        .column
          label.label IIDXID
          .control = f.text_field :iidxid, autofocus: true, placeholder: 'ex. 1234-5678', class: 'input'
      .columns
        .column
          label.label 所属
          .control = f.select :pref, User.belongs, {}, { class: 'input searchable pref' }
        .column
          label.label 段位
          .control = f.select :grade, User.dan, {}, { class: 'input searchable grade' }
      .columns
        .column
          label.label パスワード
          .control = f.password_field :password, autocomplete: 'off', placeholder: "パスワード(#{@minimum_password_length}文字以上)", class: 'input'
        .column
          label.label パスワード確認用
          .control = f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'パスワード(確認用)', class: 'input'
      .field
        button.button.is-primary = icon 'floppy-o', submit
        = link_to admin_user_path(user.id), class: 'button is-danger', data: { confirm: '本当に削除してよろしいですか？' }, method: :delete, remote: true
          = icon 'trash', '削除'
    button.modal-close.is-large aria-label='close' onclick='handleCloseUserModal()'

app/views/admin/users/_list.html.slim
table.table.is-striped
  thead
    tr
      th style="width: 150px;"
        = link_to new_admin_user_path, class: 'button is-small is-primary', remote: true do
          = icon 'plus', '作成'
      th = sort_link(@q, :id, 'id')
      th = sort_link(@q, :username, 'username')
      th = sort_link(@q, :email, 'email')
      th = sort_link(@q, :djname, 'DJNAME')
      th = sort_link(@q, :iidxid, 'IIDXID')
      th = sort_link(@q, :pref, '所属')
      th = sort_link(@q, :grade, '段位')
      th = sort_link(@q, :sign_in_count, '利用数')
      th = sort_link(@q, :current, '現在')
  tbody
    - users.each do |user|
      - user = user.decorate
      tr
        td
          - unless user.access_locked?
            = link_to edit_admin_user_path(user.id), class: 'button is-small is-success', remote: true
              = icon 'edit', '編集'
            = link_to lock_admin_user_path(user.id), class: 'button is-small', method: :post, remote: true
              = icon 'lock', '無効化'
            = link_to login_admin_user_path(user.id), class: 'button is-small is-primary'
              = icon 'sign-in-alt', 'ログイン'
          - else
            = link_to unlock_admin_user_path(user.id), class: 'button is-small is-primary', method: :post, remote: true
              = icon 'level-up-alt', '有効化'
            = link_to admin_user_path(user.id), class: 'button is-small is-danger', method: :delete, remote: true
              = icon 'trash', '削除'
        td = user.id
        td = user.username
        td = user.email
        td = user.djname
        td = user.iidxid
        td = user.pref
        td = user.grade
        td = user.sign_in_count
        td = user.current

app/views/admin/users/index.html.slim
- @title = 'ユーザ管理'

h3.subtitle.is-3 = icon 'users', @title

= search_form_for [:admin, @q] do |f|
  = icon 'search', '絞込検索'
  .columns
    .column
      label.label DJNAME
      .control = f.search_field :djname_cont, class: 'input'
    .column
      label.label IIDXID
      .control = f.search_field :iidxid_cont, class: 'input'
    .column
      label.label email
      .control = f.search_field :email_eq, class: 'input'
  .field
    label.label 所属
    .control = f.collection_check_boxes :pref_in, check_boxes_prefs, :pref, :pref_name, {}, class: 'is-checkradio is-info is-circle'
  .field
    button.button.is-primary type='submit' = icon 'search', '検索'
hr
= paginate @users
#user-modal
= render partial: 'admin/users/list', locals: { users: @users }
= paginate @users

app/views/admin/users/reload.js.erb
<% if @user.errors.empty? %>
  location.reload()
<% else %>
  alert('<%= escape_javascript @user.errors.full_messages.join("\n") %>')
<% end %>

app/views/admin/users/show_modal_form.js.erb
document.querySelector('#user-modal').innerHTML = '<%= escape_javascript(render partial: 'admin/users/form', locals: { user: @user }) %>';
document.querySelector('#user-modal').className = 'modal is-active';
$('.searchable').select2();
function handleCloseUserModal() {
  document.querySelector('#user-modal').className = 'modal';
}